[package]
name = "cbr-provider"
description = "CBR's Combraton Protocol provider: core/1 over the stream binding."
edition.workspace = true
version.workspace = true
publish.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "cbr-provider"
path = "src/main.rs"

[dependencies]
cbr-encoding = { path = "../cbr-encoding" }
